<?php $dataTemplate = $block->getWidgetDisplay() ?>
<html>
    <head>
        <script src="<?php echo $block->escapeHtml($block->getWidgetJsUrl()) ?>"></script>
        <link href="<?php echo $block->escapeHtml($block->getWidgetCssUrl()) ?>" rel="stylesheet" />
    </head>
    <body>
        <?php if($dataTemplate == \Monext\Payline\PaylineApi\Constants::PAYMENT_WIDGET_DISPLAY_LIGHTBOX) : ?>
        <div id="PaylineWidget" data-token="<?php echo $block->escapeHtml($block->getToken()) ?>"/>
        <?php else : ?>
        <div id="PaylineWidget" data-token="<?php echo $block->escapeHtml($block->getToken()) ?>" data-template="<?php echo $block->escapeHtml($dataTemplate) ?>"/>
        <?php endif ?>
    </body>
</html>
